transform_tolerance: 0.2
obstacle_range: 1.9
raytrace_range: 2.1
robot_radius: 0.35 
inflation_radius: 0.45 

observation_sources:  base_scan  inclined_cloud sonar_cloud

base_scan: {sensor_frame: base_laser_link, data_type: LaserScan, topic: /scan_filtered , expected_update_rate: 0.3,
  observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: -0.1, max_obstalce_height: 0.4}

vos: {sensor_frame: map, data_type: PointCloud, topic: /vo_cloud , expected_update_rate: 12.0, 
  observation_persistence: 0.0, marking: true, clearing: false, obstacle_range: 50.0, min_obstacle_height: 0.00, max_obstalce_height: 2.0}

inclined_cloud: {sensor_frame: base_torso_laser_link, data_type: PointCloud2, topic: /hokuyo_cloud , expected_update_rate: 1.0,
  observation_persistence: 5.0, marking: true, clearing: true, min_obstacle_height: 0.31, max_obstalce_height: 1.5}

sonar_cloud: {sensor_frame: base_link, data_type: PointCloud2, topic: /sonar_cloud , expected_update_rate: 1.0,
  observation_persistence: 5.0, marking: true, clearing: true, min_obstacle_height: 0.1, max_obstalce_height: 1.5}

