transform_tolerance: 0.2
obstacle_range: 2.0
raytrace_range: 2.5

observation_sources:  base_scan #dense_scan sonar_cloud sonar_max_range_cloud 

base_scan: {sensor_frame: base_laser_link, data_type: LaserScan, topic: /base_scan_throttle , expected_update_rate: 0.3,
  observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: -0.08, max_obstalce_height: 2.0}

dense_scan: {sensor_frame: base_laser_link, data_type: PointCloud, topic: /dense_laser_cloud , expected_update_rate: 0.3,
  observation_persistence: 0.0, marking: false, clearing: true, min_obstacle_height: -0.08, max_obstalce_height: 2.0}

sonar_cloud: {sensor_frame: base_link, data_type: PointCloud, topic: /sonar_cloud, expected_update_rate: 0.3,
  observation_persistence: 0.4, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstalce_height: 2.0}

sonar_max_range_cloud: {sensor_frame: base_link, data_type: PointCloud, topic: /sonar_max_range_cloud, expected_update_rate: 0.3,
  observation_persistence: 0.4, marking: false, clearing: true, min_obstacle_height: 0.0, max_obstalce_height: 2.0}
