#Independent settings for the planner's costmap
global_costmap: 
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 1.0
  publish_frequency: 0.0
  static_map: true
  inflation_radius: 0.80
  robot_radius: 0.60
