# Independent settings for the planner's costmap
global_costmap:
  map_type: costmap

  global_frame: map
  robot_base_frame: base_link

  update_frequency: 1.0
  publish_frequency: 1.0

  static_map: true
  map_topic: vo_map
  track_unknown_space: true
  unknown_cost_value: 255

  robot_radius: 0.80
  inflation_radius: 0.81
  cost_scaling_factor: 2.0
