# Independent settings for the planner's costmap
global_costmap:
  map_type: costmap

  global_frame    : map
  robot_base_frame: base_footprint

  update_frequency : 1.0
  publish_frequency: 1.0

  transform_tolerance: 0.2

  resolution: 0.05

  track_unknown_space: true
  unknown_cost_value : 255

  robot_radius       : 0.25
  cost_scaling_factor: 2.0

  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - name: sensor_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: footprint_layer
      type: 'costmap_2d::FootprintLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'

  static_layer:
    enabled  : true
    map_topic: vo_map

  sensor_layer:
    enabled: true
    observation_sources: base_scan #sonar_cloud #ir_cloud

    base_scan:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: scan
      expected_update_rate: 0.3
      observation_persistence: 0.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 5.5
      obstacle_range: 5.0
      min_obstacle_height: -0.1
      max_obstacle_height: 0.2

    sonar_cloud:
      sensor_frame: base_link
      data_type: PointCloud2
      topic: sonar_cloud
      expected_update_rate: 1.0
      observation_persistence: 0.0
      marking: true
      clearing: true
      raytrace_range: 4.5
      obstacle_range: 3.0
      min_obstacle_height: 0.1
      max_obstacle_height: 1.8

    ir_cloud:
      sensor_frame: base_link
      data_type: PointCloud2
      topic: ir_cloud
      expected_update_rate: 1.0
      observation_persistence: 0.0
      marking: true
      clearing: true
      raytrace_range: 2.0
      obstacle_range: 1.7
      min_obstacle_height: 0.2
      max_obstacle_height: 1.8

  footprint_layer:
    enabled: true

  inflation_layer:
    enabled         : true
    robot_radius    : 0.25
    inflation_radius: 0.30
