controller_frequency: 10.0
controller_patience : 10.0
planner_frequency   :  0.5

oscillation_timeout : 10.0
oscillation_distance:  0.2

recovery_behavior_enabled: true
shutdown_costmaps        : false
