recovery_behaviors:
  - name: 'super_conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate'
    type: rotate_recovery/RotateRecovery


super_conservative_reset:
  reset_distance: 5.0
  layer_names: ["obstacle_laser_layer"]

conservative_reset:
  reset_distance: 3.0
  layer_names: ["obstacle_laser_layer"]

aggressive_reset:
  reset_distance: 1.2
  layer_names: ["obstacle_laser_layer"]

rotate:
  max_rotational_vel: 0.6
