min_sensor_dist: .05
self_see_default_padding: .01
self_see_default_scale: 1.0
self_see_links:
  - name: hand_left_palm_link
    padding: 0.10
  - name: hand_left_middle_3_link
    padding: 0.10
  - name: hand_left_thumb_link
    padding: 0.10
  - name: hand_right_palm_link
    padding: 0.10
  - name: hand_right_middle_3_link
    padding: 0.10
  - name: hand_right_thumb_link
    padding: 0.10
